name: CICD pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Initialising the Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Maven build
      run: mvn -B package --file pom.xml

